### ISSUE TITLE
Moving the css-snippets folder from vault root to the .obsidian directory

### ISSUE THREAD

**Issue by hxhc** [jdbrice/obsidian-css-snippets#1]
The plugin needs to put .css files into css-snippets in the vault root, and this makes the `css-snippets` folder is shown in the Obsidian left pannel. 
![](https://i.loli.net/2020/12/04/7kPrdTM5Hwu6SeV.png)
What about to move the folder into `.obsidian` to make it invisible in the left pannel.

**Comment by timjore** [comment]
This is a great plugin!

> What about to move the folder into `.obsidian` to make it invisible in the left panel.

This would help to minimize the clutter in the folder display of a vault. Putting the css snippets in `.obsidian/css-snippets` would provide a clean solution.

**Comment by Parlazo** [comment]
Custom folder would be great
